
name: Automatic Coverage Reporting Upon Merge
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm run cover:report

      - name: Run coverage extraction script
        id: extract_coverage
        run: |
          COVERAGE=$(node extractCoverage.js)
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV 

      - name: Update README.md with coverage value
        run: |
          sed -i "s|!\\[Coverage Badge\\](.*)|![Coverage Badge](https://img.shields.io/badge/coverage-${{ env.COVERAGE }}%25-green)|" README.md
      
          git add README.md
          git commit -m "Automated commit"

      - name: Push changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git push origin main
      

