
name: Automatic Coverage Reporting Upon Merge
on:
  push:
    branches:
      - main
    if: github.actor != 'github-actions[bot]'

permissions:
  contents: write  # Ensure GITHUB_TOKEN has write access

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm run cover:report

      - name: Run coverage extraction script
        id: extract_coverage
        run: |
          COVERAGE=$(node extractCoverage.js)
          COVERAGE=$(echo $COVERAGE | xargs)  # Trim any extra spaces
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Print Coverage Value
        run: |
          echo "Coverage Value is: ${{ env.COVERAGE }}"

      - name: Set Git user identity
        run: |
          git config --global user.email "skyehaik@rogers.com"
          git config --global user.name "Skye Haik"

      - name: Mark the repository as safe
        run: git config --global --add safe.directory /__w/defer_until/defer_until

      - name: Update README.md with coverage value
        run: |
          git checkout -b covBranch/main
          git pull origin covBranch/main || echo "No remote changes to pull"
          sed -i "s|!\\[Coverage Badge\\](.*)|![Coverage Badge](https://img.shields.io/badge/coverage-${{ env.COVERAGE }}%25-green)|" README.md

      - name: Push changes to main
        run: |
          git add README.md
          git commit -m "Automated commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://github.com/cli/cli/releases/download/v2.21.0/gh_2.21.0_linux_amd64.deb -o gh.deb
          dpkg -i gh.deb
          rm gh.deb


      - name: Automatic PR & Merge
        run: |
           gh pr create --title "Update Coverage Badge" --body "Automated PR to update the coverage badge" --head covBranch/main --base main
           gh pr merge --auto --delete-branch --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
