
name: Automatic Coverage Reporting Upon Merge
on:
  push:
    branches:
      - main

permissions:
  contents: write  # Ensure GITHUB_TOKEN has write access
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm run cover:report

      - name: Run coverage extraction script
        id: extract_coverage
        run: |
          COVERAGE=$(node extractCoverage.js)

      - name: Print Coverage Value
        run: |
          echo "Coverage Value is: ${{ env.COVERAGE }}"

      - name: Set Git user identity
        run: |
          git config --global user.email "skyehaik@rogers.com"
          git config --global user.name "skyehaik"

      - name: Mark the repository as safe
        run: git config --global --add safe.directory /__w/defer_until/defer_until

      - name: Disable default GitHub token
        run: |
          git config --global --unset credential.helper

      - name: Verify remote URL
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          echo "Current remote URL:"
          git remote -v

      - name: Echo the PAT (masked for safety)
        run: |
          echo "Using PAT: ${{ secrets.PAT }}"
          echo "::add-mask::${{ secrets.PAT }}"  # This masks the token in the logs


      - name: Push changes to main
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git add badge.json
          git commit -m "Automated commit"
          git push origin main
      
