# Workflow Name
name: Automatic Coverage Reporting Upon Merge
# Set Event Which Triggers Workflow (Pull Request on Main or Push to Main)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main

jobs:
  test:
    # Using Ubuntun (most common OS used with github actions but can also linux, and some other options)
    runs-on: ubuntu-latest
    container:
      # Using Node JS Version 22
      image: node:22
    steps:
      # Checkout Code
      - uses: actions/checkout@v3
        with:
          node-version: 22
      # Install Dependencies
      - run: npm ci
      # Run Coverage Report
      - run: npm run coverage:report

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

